$activeBorderColor = rgb(9ccc85)
$inactiveBorderColor = rgb(2a3330)

general {
    col.active_border = $activeBorderColor
    col.inactive_border = $inactiveBorderColor
}

group {
    col.border_active = $activeBorderColor
    col.border_inactive = $inactiveBorderColor
}
