accent = "#5eb3d1"
cursor = "#d6e6f0"
foreground = "#d6e6f0"
background = "#0a1824"
selection_foreground = "#0a1824"
selection_background = "#5eb3d1"

color0 = "#1a2a38"
color1 = "#d97878"
color2 = "#7fb8a8"
color3 = "#d9c482"
color4 = "#5eb3d1"
color5 = "#8a9dc9"
color6 = "#7acdd9"
color7 = "#d6e6f0"
color8 = "#3a4d60"
color9 = "#e89090"
color10 = "#95ccbe"
color11 = "#ecd49a"
color12 = "#7acce8"
color13 = "#a3b5d9"
color14 = "#92dce6"
color15 = "#eaf2f6"
