$activeBorderColor = rgb(5eb3d1)
$inactiveBorderColor = rgb(1a2a38)

general {
    col.active_border = $activeBorderColor
    col.inactive_border = $inactiveBorderColor
}

group {
    col.border_active = $activeBorderColor
    col.border_inactive = $inactiveBorderColor
}
